language: generic
sudo: required
services:
  - docker

install: true

env:
  - GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=load-test;

script:
  - set -e
  - curl -o docker-compose.yml -sSL https://raw.githubusercontent.com/microservices-demo/microservices-demo/master/deploy/docker-compose/docker-compose.yml
  - docker-compose -f docker-compose.yml up -d
  - docker build -t ${GROUP}/${REPO}:${COMMIT} .
  - docker run --rm --net loadtest_default -t weaveworksdemos/load-test -d 180 -h edge-router -c 250 -r 2500

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - ./push.sh
