apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
spec:
  ports:
  - name: "27022"
    port: 27022
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-reservation
status:
  loadBalancer: {}
