apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: profile
  name: profile
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: profile
    spec:
      containers:
      - command:
        - profile
        image: khv129/hotel_reserv_profile_single_node
        name: hotel-reserv-profile
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
