apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: reservation
  name: reservation
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: reservation
    spec:
      containers:
      - command:
        - reservation
        image: khv129/hotel_reserv_rsv_single_node
        name: hotel-reserv-reservation
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
