apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
      - name: payment
        image: khv129/sockshop_payment
        ports:
        - containerPort: 8084
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.istio-system.svc.cluster.local 
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
  namespace: sock-shop
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    nodePort: 30084
    targetPort: 8084
  selector:
    name: payment
---
